### PR TITLE
ignore encode error

### PR DESCRIPTION
**Pull request by pandada8**

### CODE REVIEW

**Comment by lilydjwg** [comment]
why ignore?

**Comment by pandada8** [comment]
some pages have bad encoded char in the page, which cause parsing fail
```
  File "/Users/pan/repo/forked/fetchtitle/fetchtitle/__init__.py", line 130, in handle_data
        data = data.encode('latin1') # encode back
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2019' in position 22: ordinal not in range(256)
```

**Comment by lilydjwg** [comment]
This has been fixed via https://github.com/lilydjwg/fetchtitle/commit/84dc4825a414d90401dd62daf7948f7feb426325.

**Comment by lilydjwg** [comment]
The parser would never fail with this, if Python devs had been sane to at least document changed behaviour :-(

**Pull request closed without merging**
